// frontend/src/lib/components/SeriesCard.svelte
<script lang="ts">
    import api from '@lib/api';

    export let series: Series;
</script>

<a href={`/series/${series.id}`} class="col-span-1 rounded-md bg-gray-800">
    <!-- on:error={(err) => console.log({ series, err })} -->
    <!-- on:error={(err) => loadError = true} -->
    <!-- TODO: figure out why this was not working, causing multiple to fail
      when in reality only one failed -->

    <div
        class="hover:border-brand rounded-t-md border border-transparent px-1.5 transition-all duration-200"
    >
        <!-- Trying to keep the 3:2 aspect ratio of comic books -->
        <img
            id={String(series.id)}
            alt="{series.title} thumbnail"
            class="h-72 w-auto max-w-[12rem] object-scale-down"
            src={api.series.getSeriesThumbnail(series.id)}
            on:error={(err) => {
                // @ts-ignore: TODO add fallback
                err.target.src = '/favicon.png';
            }}
        />
    </div>

    <div class="p-2">
        <h3 class="text-gray-100">{series.title}</h3>
        <p class="text-gray-100">{series.book_count} books</p>
    </div>
</a>

// react/src/components/SeriesCard.tsx
import { Box, Text } from '@chakra-ui/react';
import React from 'react';
import client from '~api/client';
import { getSeriesById, getSeriesThumbnail } from '~api/query/series';

interface Props extends Series {}

export default function SeriesCard({ ...series }: Props) {
	const prefetchSeries = async () =>
		await client.prefetchQuery(['getSeries', series.id], () => getSeriesById(series.id), {
			staleTime: 10 * 1000,
		});

	return (
		<a
			href={`/series/${series.id}`}
			className="hover:border-brand col-span-1 rounded-md rounded-t-md border border-transparent bg-gray-800 transition-all duration-200"
			onMouseEnter={prefetchSeries}
		>
			<Box px={1.5}>
				<img
					id={String(series.id)}
					alt={`${series.title} thumbnail`}
					className="h-72 w-auto max-w-[12rem] object-scale-down"
					src={getSeriesThumbnail(series.id)}
					onError={(err) => {
						// @ts-ignore
						err.target.src = '/src/favicon.png';
					}}
				/>
			</Box>

			<Box p={2}>
				<h3 className="text-gray-100">{series.title}</h3>
				<Text>{series.book_count} books</Text>
			</Box>
		</a>
	);
}
