// frontend/src/components/media/MediaCard.tsx
import React from 'react';
import { Box } from '@chakra-ui/react';
import client from '~api/client';
import { getMediaById, getMediaThumbnail } from '~api/query/media';

interface Props extends MediaWithProgress {}

export default function MediaCard({ ...media }: Props) {
	const prefetchMedia = async () =>
		await client.prefetchQuery(['getMediaById', media.id], () => getMediaById(media.id), {
			staleTime: 10 * 1000,
		});

	return (
		<a
			href={`/books/${media.id}`}
			className="hover:border-brand rounded-md rounded-t-md border border-transparent bg-gray-800 transition-all duration-200"
			onMouseEnter={prefetchMedia}
		>
			<Box px={1.5}>
				<img
					id={String(media.id)}
					alt={`${media.name} thumbnail`}
					className="h-72 w-auto max-w-[12rem] object-scale-down"
					src={getMediaThumbnail(media.id)}
					onError={(err) => {
						// @ts-ignore
						err.target.src = '/src/favicon.png';
					}}
				/>
			</Box>

			<div className="max-w-[11.5rem] p-2">
				<h3 title={media.name} className="text-gray-100">
					{media.name}
				</h3>
			</div>
		</a>
	);
}

// frontend/src/lib/components/MediaCard.svelte
<script lang="ts">
    import api from '@lib/api';

    export let media: MediaWithProgress;
</script>

<!-- TODO: href based on next page -->
<a href={`/book/${media.id}`} class="col-span-1 rounded-md bg-gray-800">
    <!-- on:error={(err) => console.log({ series, err })} -->
    <!-- on:error={(err) => loadError = true} -->
    <!-- TODO: figure out why this was not working, causing multiple to fail
      when in reality only one failed -->

    <div
        class="hover:border-brand rounded-t-md border border-transparent px-1.5 transition-all duration-200"
    >
        <!-- Trying to keep the 3:2 aspect ratio of comic books -->
        <img
            id={String(media.id)}
            alt="{media.name} thumbnail"
            class="h-72 w-auto max-w-[12rem] object-scale-down"
            src={api.media.getMediaThumbnail(media.id)}
            on:error={(err) => {
                // @ts-ignore: TODO add fallback
                err.target.src = '/favicon.png';
            }}
        />
    </div>

    <div class="p-2">
        <h3 class="text-gray-100">{media.name}</h3>
    </div>
</a>
